// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Archive(arg1, arg2) {
  return window['go']['app']['App']['Archive'](arg1, arg2);
}

export function Block(arg1, arg2) {
  return window['go']['app']['App']['Block'](arg1, arg2);
}

export function Connect() {
  return window['go']['app']['App']['Connect']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['app']['App']['CreateGroup'](arg1, arg2);
}

export function DeleteChat(arg1) {
  return window['go']['app']['App']['DeleteChat'](arg1);
}

export function DeleteMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['DeleteMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadMedia(arg1, arg2) {
  return window['go']['app']['App']['DownloadMedia'](arg1, arg2);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['EditMessage'](arg1, arg2, arg3);
}

export function FollowChannel(arg1) {
  return window['go']['app']['App']['FollowChannel'](arg1);
}

export function Forward(arg1, arg2, arg3) {
  return window['go']['app']['App']['Forward'](arg1, arg2, arg3);
}

export function GetArchivedChats() {
  return window['go']['app']['App']['GetArchivedChats']();
}

export function GetChannelMessages(arg1) {
  return window['go']['app']['App']['GetChannelMessages'](arg1);
}

export function GetChannels() {
  return window['go']['app']['App']['GetChannels']();
}

export function GetChats() {
  return window['go']['app']['App']['GetChats']();
}

export function GetCommunities() {
  return window['go']['app']['App']['GetCommunities']();
}

export function GetContactAbout(arg1) {
  return window['go']['app']['App']['GetContactAbout'](arg1);
}

export function GetGroupInfo(arg1) {
  return window['go']['app']['App']['GetGroupInfo'](arg1);
}

export function GetMessageInfo(arg1, arg2) {
  return window['go']['app']['App']['GetMessageInfo'](arg1, arg2);
}

export function GetMessages(arg1) {
  return window['go']['app']['App']['GetMessages'](arg1);
}

export function GetMessagesBefore(arg1, arg2) {
  return window['go']['app']['App']['GetMessagesBefore'](arg1, arg2);
}

export function GetPinned(arg1) {
  return window['go']['app']['App']['GetPinned'](arg1);
}

export function GetProfile() {
  return window['go']['app']['App']['GetProfile']();
}

export function GetProfilePic(arg1) {
  return window['go']['app']['App']['GetProfilePic'](arg1);
}

export function GetStarred() {
  return window['go']['app']['App']['GetStarred']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetStatuses() {
  return window['go']['app']['App']['GetStatuses']();
}

export function GroupInviteLink(arg1, arg2) {
  return window['go']['app']['App']['GroupInviteLink'](arg1, arg2);
}

export function LeaveCommunity(arg1) {
  return window['go']['app']['App']['LeaveCommunity'](arg1);
}

export function LeaveGroup(arg1) {
  return window['go']['app']['App']['LeaveGroup'](arg1);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function MarkRead(arg1, arg2, arg3) {
  return window['go']['app']['App']['MarkRead'](arg1, arg2, arg3);
}

export function MarkUnread(arg1, arg2) {
  return window['go']['app']['App']['MarkUnread'](arg1, arg2);
}

export function Mute(arg1, arg2) {
  return window['go']['app']['App']['Mute'](arg1, arg2);
}

export function MuteChannel(arg1, arg2) {
  return window['go']['app']['App']['MuteChannel'](arg1, arg2);
}

export function Notify(arg1, arg2) {
  return window['go']['app']['App']['Notify'](arg1, arg2);
}

export function OpenChat(arg1) {
  return window['go']['app']['App']['OpenChat'](arg1);
}

export function Pin(arg1, arg2) {
  return window['go']['app']['App']['Pin'](arg1, arg2);
}

export function PinMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['PinMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function PostTextStatus(arg1) {
  return window['go']['app']['App']['PostTextStatus'](arg1);
}

export function React(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['React'](arg1, arg2, arg3, arg4, arg5);
}

export function Reply(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['Reply'](arg1, arg2, arg3, arg4, arg5);
}

export function RequestPhotos(arg1) {
  return window['go']['app']['App']['RequestPhotos'](arg1);
}

export function SearchMessages(arg1) {
  return window['go']['app']['App']['SearchMessages'](arg1);
}

export function SendMedia(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SendMedia'](arg1, arg2, arg3, arg4, arg5);
}

export function SendText(arg1, arg2) {
  return window['go']['app']['App']['SendText'](arg1, arg2);
}

export function SendTextMentioned(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendTextMentioned'](arg1, arg2, arg3);
}

export function SendTyping(arg1, arg2) {
  return window['go']['app']['App']['SendTyping'](arg1, arg2);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['app']['App']['ServeHTTP'](arg1, arg2);
}

export function SetGroupPhoto(arg1, arg2) {
  return window['go']['app']['App']['SetGroupPhoto'](arg1, arg2);
}

export function SetGroupSubject(arg1, arg2) {
  return window['go']['app']['App']['SetGroupSubject'](arg1, arg2);
}

export function SetMyAbout(arg1) {
  return window['go']['app']['App']['SetMyAbout'](arg1);
}

export function SetMyName(arg1) {
  return window['go']['app']['App']['SetMyName'](arg1);
}

export function StarMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StarMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function Translate(arg1, arg2) {
  return window['go']['app']['App']['Translate'](arg1, arg2);
}

export function UnfollowChannel(arg1) {
  return window['go']['app']['App']['UnfollowChannel'](arg1);
}

export function UpdateGroupParticipants(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateGroupParticipants'](arg1, arg2, arg3);
}
