// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Archive(arg1, arg2) {
  return window['go']['app']['App']['Archive'](arg1, arg2);
}

export function Block(arg1, arg2) {
  return window['go']['app']['App']['Block'](arg1, arg2);
}

export function ClearChat(arg1) {
  return window['go']['app']['App']['ClearChat'](arg1);
}

export function Connect() {
  return window['go']['app']['App']['Connect']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['app']['App']['CreateGroup'](arg1, arg2);
}

export function DeleteChat(arg1) {
  return window['go']['app']['App']['DeleteChat'](arg1);
}

export function DeleteMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['DeleteMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadMedia(arg1, arg2) {
  return window['go']['app']['App']['DownloadMedia'](arg1, arg2);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['EditMessage'](arg1, arg2, arg3);
}

export function ExportChat(arg1) {
  return window['go']['app']['App']['ExportChat'](arg1);
}

export function FetchRemoteMedia(arg1) {
  return window['go']['app']['App']['FetchRemoteMedia'](arg1);
}

export function FollowChannel(arg1) {
  return window['go']['app']['App']['FollowChannel'](arg1);
}

export function FollowChannelByJID(arg1) {
  return window['go']['app']['App']['FollowChannelByJID'](arg1);
}

export function Forward(arg1, arg2, arg3) {
  return window['go']['app']['App']['Forward'](arg1, arg2, arg3);
}

export function GetArchivedChats() {
  return window['go']['app']['App']['GetArchivedChats']();
}

export function GetBlockedContacts() {
  return window['go']['app']['App']['GetBlockedContacts']();
}

export function GetCalls() {
  return window['go']['app']['App']['GetCalls']();
}

export function GetChannelMessages(arg1) {
  return window['go']['app']['App']['GetChannelMessages'](arg1);
}

export function GetChannels() {
  return window['go']['app']['App']['GetChannels']();
}

export function GetChatMedia(arg1) {
  return window['go']['app']['App']['GetChatMedia'](arg1);
}

export function GetChats() {
  return window['go']['app']['App']['GetChats']();
}

export function GetCommunities() {
  return window['go']['app']['App']['GetCommunities']();
}

export function GetContactAbout(arg1) {
  return window['go']['app']['App']['GetContactAbout'](arg1);
}

export function GetContactProfile(arg1) {
  return window['go']['app']['App']['GetContactProfile'](arg1);
}

export function GetContacts() {
  return window['go']['app']['App']['GetContacts']();
}

export function GetGroupInfo(arg1) {
  return window['go']['app']['App']['GetGroupInfo'](arg1);
}

export function GetGroupRequests(arg1) {
  return window['go']['app']['App']['GetGroupRequests'](arg1);
}

export function GetLinkPreview(arg1) {
  return window['go']['app']['App']['GetLinkPreview'](arg1);
}

export function GetMessageInfo(arg1, arg2) {
  return window['go']['app']['App']['GetMessageInfo'](arg1, arg2);
}

export function GetMessages(arg1) {
  return window['go']['app']['App']['GetMessages'](arg1);
}

export function GetMessagesBefore(arg1, arg2) {
  return window['go']['app']['App']['GetMessagesBefore'](arg1, arg2);
}

export function GetPinned(arg1) {
  return window['go']['app']['App']['GetPinned'](arg1);
}

export function GetPollVotes(arg1) {
  return window['go']['app']['App']['GetPollVotes'](arg1);
}

export function GetPrivacy() {
  return window['go']['app']['App']['GetPrivacy']();
}

export function GetProfile() {
  return window['go']['app']['App']['GetProfile']();
}

export function GetRecommendedChannels(arg1) {
  return window['go']['app']['App']['GetRecommendedChannels'](arg1);
}

export function GetRetention() {
  return window['go']['app']['App']['GetRetention']();
}

export function GetStarred() {
  return window['go']['app']['App']['GetStarred']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetStatusViewers(arg1) {
  return window['go']['app']['App']['GetStatusViewers'](arg1);
}

export function GetStatuses() {
  return window['go']['app']['App']['GetStatuses']();
}

export function GroupInviteLink(arg1, arg2) {
  return window['go']['app']['App']['GroupInviteLink'](arg1, arg2);
}

export function IsOnWhatsApp(arg1) {
  return window['go']['app']['App']['IsOnWhatsApp'](arg1);
}

export function JoinGroupLink(arg1) {
  return window['go']['app']['App']['JoinGroupLink'](arg1);
}

export function LeaveCommunity(arg1) {
  return window['go']['app']['App']['LeaveCommunity'](arg1);
}

export function LeaveGroup(arg1) {
  return window['go']['app']['App']['LeaveGroup'](arg1);
}

export function LinkWithPhone(arg1) {
  return window['go']['app']['App']['LinkWithPhone'](arg1);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function MarkRead(arg1, arg2, arg3) {
  return window['go']['app']['App']['MarkRead'](arg1, arg2, arg3);
}

export function MarkUnread(arg1, arg2) {
  return window['go']['app']['App']['MarkUnread'](arg1, arg2);
}

export function Mute(arg1, arg2) {
  return window['go']['app']['App']['Mute'](arg1, arg2);
}

export function MuteChannel(arg1, arg2) {
  return window['go']['app']['App']['MuteChannel'](arg1, arg2);
}

export function Notify(arg1, arg2) {
  return window['go']['app']['App']['Notify'](arg1, arg2);
}

export function OpenChat(arg1) {
  return window['go']['app']['App']['OpenChat'](arg1);
}

export function Pin(arg1, arg2) {
  return window['go']['app']['App']['Pin'](arg1, arg2);
}

export function PinMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['PinMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function PostMediaStatus(arg1, arg2, arg3) {
  return window['go']['app']['App']['PostMediaStatus'](arg1, arg2, arg3);
}

export function PostTextStatus(arg1) {
  return window['go']['app']['App']['PostTextStatus'](arg1);
}

export function PreviewGroupLink(arg1) {
  return window['go']['app']['App']['PreviewGroupLink'](arg1);
}

export function React(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['React'](arg1, arg2, arg3, arg4, arg5);
}

export function ReactChannel(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ReactChannel'](arg1, arg2, arg3, arg4);
}

export function RejectCall(arg1, arg2) {
  return window['go']['app']['App']['RejectCall'](arg1, arg2);
}

export function RemoveContactLabel(arg1) {
  return window['go']['app']['App']['RemoveContactLabel'](arg1);
}

export function Reply(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['Reply'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveContactLabel(arg1, arg2) {
  return window['go']['app']['App']['SaveContactLabel'](arg1, arg2);
}

export function SearchGifs(arg1, arg2) {
  return window['go']['app']['App']['SearchGifs'](arg1, arg2);
}

export function SearchMessages(arg1) {
  return window['go']['app']['App']['SearchMessages'](arg1);
}

export function SearchStickers(arg1, arg2) {
  return window['go']['app']['App']['SearchStickers'](arg1, arg2);
}

export function SendContact(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendContact'](arg1, arg2, arg3);
}

export function SendGif(arg1, arg2) {
  return window['go']['app']['App']['SendGif'](arg1, arg2);
}

export function SendLocation(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendLocation'](arg1, arg2, arg3, arg4);
}

export function SendMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['SendMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SendPoll(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendPoll'](arg1, arg2, arg3, arg4);
}

export function SendSticker(arg1, arg2) {
  return window['go']['app']['App']['SendSticker'](arg1, arg2);
}

export function SendText(arg1, arg2) {
  return window['go']['app']['App']['SendText'](arg1, arg2);
}

export function SendTextMentioned(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendTextMentioned'](arg1, arg2, arg3);
}

export function SendTyping(arg1, arg2) {
  return window['go']['app']['App']['SendTyping'](arg1, arg2);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['app']['App']['ServeHTTP'](arg1, arg2);
}

export function SetDisappearing(arg1, arg2) {
  return window['go']['app']['App']['SetDisappearing'](arg1, arg2);
}

export function SetGroupAddMode(arg1, arg2) {
  return window['go']['app']['App']['SetGroupAddMode'](arg1, arg2);
}

export function SetGroupAnnounce(arg1, arg2) {
  return window['go']['app']['App']['SetGroupAnnounce'](arg1, arg2);
}

export function SetGroupDescription(arg1, arg2) {
  return window['go']['app']['App']['SetGroupDescription'](arg1, arg2);
}

export function SetGroupJoinApproval(arg1, arg2) {
  return window['go']['app']['App']['SetGroupJoinApproval'](arg1, arg2);
}

export function SetGroupLocked(arg1, arg2) {
  return window['go']['app']['App']['SetGroupLocked'](arg1, arg2);
}

export function SetGroupPhoto(arg1, arg2) {
  return window['go']['app']['App']['SetGroupPhoto'](arg1, arg2);
}

export function SetGroupSubject(arg1, arg2) {
  return window['go']['app']['App']['SetGroupSubject'](arg1, arg2);
}

export function SetMyAbout(arg1) {
  return window['go']['app']['App']['SetMyAbout'](arg1);
}

export function SetMyName(arg1) {
  return window['go']['app']['App']['SetMyName'](arg1);
}

export function SetPrivacy(arg1, arg2) {
  return window['go']['app']['App']['SetPrivacy'](arg1, arg2);
}

export function SetRetention(arg1) {
  return window['go']['app']['App']['SetRetention'](arg1);
}

export function StarMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StarMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SubscribePresence(arg1) {
  return window['go']['app']['App']['SubscribePresence'](arg1);
}

export function Translate(arg1, arg2) {
  return window['go']['app']['App']['Translate'](arg1, arg2);
}

export function UnfollowChannel(arg1) {
  return window['go']['app']['App']['UnfollowChannel'](arg1);
}

export function UpdateGroupParticipants(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateGroupParticipants'](arg1, arg2, arg3);
}

export function UpdateGroupRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateGroupRequest'](arg1, arg2, arg3);
}

export function VotePoll(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['VotePoll'](arg1, arg2, arg3, arg4);
}
