// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {http} from '../models';

export function Archive(arg1:string,arg2:boolean):Promise<void>;

export function Block(arg1:string,arg2:boolean):Promise<void>;

export function Connect():Promise<void>;

export function CreateGroup(arg1:string,arg2:Array<string>):Promise<string>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function DownloadMedia(arg1:string,arg2:string):Promise<string>;

export function EditMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportChat(arg1:string):Promise<string>;

export function FetchRemoteMedia(arg1:string):Promise<string>;

export function FollowChannel(arg1:string):Promise<app.ChannelDTO>;

export function Forward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetArchivedChats():Promise<Array<app.ChatDTO>>;

export function GetBlockedContacts():Promise<Array<app.ContactRowDTO>>;

export function GetChannelMessages(arg1:string):Promise<Array<app.ChannelMsgDTO>>;

export function GetChannels():Promise<Array<app.ChannelDTO>>;

export function GetChats():Promise<Array<app.ChatDTO>>;

export function GetCommunities():Promise<Array<app.CommunityDTO>>;

export function GetContactAbout(arg1:string):Promise<string>;

export function GetContactProfile(arg1:string):Promise<app.ContactProfileDTO>;

export function GetContacts():Promise<Array<app.ContactRowDTO>>;

export function GetGroupInfo(arg1:string):Promise<app.GroupInfoDTO>;

export function GetLinkPreview(arg1:string):Promise<app.LinkPreviewDTO>;

export function GetMessageInfo(arg1:string,arg2:string):Promise<app.MsgInfoDTO>;

export function GetMessages(arg1:string):Promise<Array<app.MessageDTO>>;

export function GetMessagesBefore(arg1:string,arg2:number):Promise<Array<app.MessageDTO>>;

export function GetPinned(arg1:string):Promise<Array<app.MessageDTO>>;

export function GetPollVotes(arg1:string):Promise<app.PollVotesDTO>;

export function GetPrivacy():Promise<Record<string, string>>;

export function GetProfile():Promise<app.ProfileDTO>;

export function GetProfilePic(arg1:string):Promise<string>;

export function GetStarred():Promise<Array<app.SearchHitDTO>>;

export function GetState():Promise<string>;

export function GetStatusViewers(arg1:string):Promise<Array<app.ReceiptDTO>>;

export function GetStatuses():Promise<Array<app.StatusGroupDTO>>;

export function GroupInviteLink(arg1:string,arg2:boolean):Promise<string>;

export function LeaveCommunity(arg1:string):Promise<void>;

export function LeaveGroup(arg1:string):Promise<void>;

export function Logout():Promise<void>;

export function MarkRead(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MarkUnread(arg1:string,arg2:boolean):Promise<void>;

export function Mute(arg1:string,arg2:boolean):Promise<void>;

export function MuteChannel(arg1:string,arg2:boolean):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenChat(arg1:string):Promise<void>;

export function Pin(arg1:string,arg2:boolean):Promise<void>;

export function PinMessage(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function PostMediaStatus(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PostTextStatus(arg1:string):Promise<string>;

export function React(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ReactChannel(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function RemoveContactLabel(arg1:string):Promise<void>;

export function Reply(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RequestPhotos(arg1:Array<string>):Promise<void>;

export function SaveContactLabel(arg1:string,arg2:string):Promise<void>;

export function SearchGifs(arg1:string):Promise<Array<app.GifDTO>>;

export function SearchMessages(arg1:string):Promise<Array<app.SearchHitDTO>>;

export function SendContact(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendGif(arg1:string,arg2:string):Promise<string>;

export function SendLocation(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function SendMedia(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function SendPoll(arg1:string,arg2:string,arg3:Array<string>,arg4:number):Promise<string>;

export function SendSticker(arg1:string,arg2:string):Promise<string>;

export function SendText(arg1:string,arg2:string):Promise<string>;

export function SendTextMentioned(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SendTyping(arg1:string,arg2:boolean):Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetDisappearing(arg1:string,arg2:number):Promise<void>;

export function SetGroupDescription(arg1:string,arg2:string):Promise<void>;

export function SetGroupPhoto(arg1:string,arg2:string):Promise<void>;

export function SetGroupSubject(arg1:string,arg2:string):Promise<void>;

export function SetMyAbout(arg1:string):Promise<void>;

export function SetMyName(arg1:string):Promise<void>;

export function SetPrivacy(arg1:string,arg2:string):Promise<void>;

export function StarMessage(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function Translate(arg1:string,arg2:string):Promise<string>;

export function UnfollowChannel(arg1:string):Promise<void>;

export function UpdateGroupParticipants(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function VotePoll(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;
