// Daftar bahasa target terjemahan (kode ISO Google Translate). Sumber dideteksi
// otomatis di BE, jadi ini hanya bahasa TUJUAN. ~tak perlu install apa pun (online).
// `en` di name = nama bahasa dlm bahasa Inggris (utk pencarian latin: "japanese").
export const TRANSLATE_LANGS = [
  { code: "id", name: "Indonesia", en: "Indonesian" },
  { code: "en", name: "English", en: "English" },
  { code: "jv", name: "Basa Jawa", en: "Javanese" },
  { code: "su", name: "Basa Sunda", en: "Sundanese" },
  { code: "ms", name: "Melayu", en: "Malay" },
  { code: "ar", name: "العربية", en: "Arabic" },
  { code: "zh-CN", name: "中文 (简体)", en: "Chinese (Simplified)" },
  { code: "zh-TW", name: "中文 (繁體)", en: "Chinese (Traditional)" },
  { code: "ja", name: "日本語", en: "Japanese" },
  { code: "ko", name: "한국어", en: "Korean" },
  { code: "es", name: "Español", en: "Spanish" },
  { code: "fr", name: "Français", en: "French" },
  { code: "de", name: "Deutsch", en: "German" },
  { code: "ru", name: "Русский", en: "Russian" },
  { code: "pt", name: "Português", en: "Portuguese" },
  { code: "it", name: "Italiano", en: "Italian" },
  { code: "nl", name: "Nederlands", en: "Dutch" },
  { code: "tr", name: "Türkçe", en: "Turkish" },
  { code: "vi", name: "Tiếng Việt", en: "Vietnamese" },
  { code: "th", name: "ไทย", en: "Thai" },
  { code: "hi", name: "हिन्दी", en: "Hindi" },
  { code: "bn", name: "বাংলা", en: "Bengali" },
  { code: "ta", name: "தமிழ்", en: "Tamil" },
  { code: "te", name: "తెలుగు", en: "Telugu" },
  { code: "mr", name: "मराठी", en: "Marathi" },
  { code: "gu", name: "ગુજરાતી", en: "Gujarati" },
  { code: "kn", name: "ಕನ್ನಡ", en: "Kannada" },
  { code: "ml", name: "മലയാളം", en: "Malayalam" },
  { code: "pa", name: "ਪੰਜਾਬੀ", en: "Punjabi" },
  { code: "ur", name: "اردو", en: "Urdu" },
  { code: "fa", name: "فارسی", en: "Persian" },
  { code: "ps", name: "پښتو", en: "Pashto" },
  { code: "he", name: "עברית", en: "Hebrew" },
  { code: "fil", name: "Filipino", en: "Filipino" },
  { code: "my", name: "မြန်မာ", en: "Burmese" },
  { code: "km", name: "ខ្មែរ", en: "Khmer" },
  { code: "lo", name: "ລາວ", en: "Lao" },
  { code: "si", name: "සිංහල", en: "Sinhala" },
  { code: "ne", name: "नेपाली", en: "Nepali" },
  { code: "pl", name: "Polski", en: "Polish" },
  { code: "uk", name: "Українська", en: "Ukrainian" },
  { code: "cs", name: "Čeština", en: "Czech" },
  { code: "sk", name: "Slovenčina", en: "Slovak" },
  { code: "ro", name: "Română", en: "Romanian" },
  { code: "hu", name: "Magyar", en: "Hungarian" },
  { code: "el", name: "Ελληνικά", en: "Greek" },
  { code: "bg", name: "Български", en: "Bulgarian" },
  { code: "sr", name: "Српски", en: "Serbian" },
  { code: "hr", name: "Hrvatski", en: "Croatian" },
  { code: "sl", name: "Slovenščina", en: "Slovenian" },
  { code: "sv", name: "Svenska", en: "Swedish" },
  { code: "da", name: "Dansk", en: "Danish" },
  { code: "no", name: "Norsk", en: "Norwegian" },
  { code: "fi", name: "Suomi", en: "Finnish" },
  { code: "et", name: "Eesti", en: "Estonian" },
  { code: "lv", name: "Latviešu", en: "Latvian" },
  { code: "lt", name: "Lietuvių", en: "Lithuanian" },
  { code: "ca", name: "Català", en: "Catalan" },
  { code: "eu", name: "Euskara", en: "Basque" },
  { code: "gl", name: "Galego", en: "Galician" },
  { code: "af", name: "Afrikaans", en: "Afrikaans" },
  { code: "sw", name: "Kiswahili", en: "Swahili" },
  { code: "ha", name: "Hausa", en: "Hausa" },
  { code: "yo", name: "Yorùbá", en: "Yoruba" },
  { code: "ig", name: "Igbo", en: "Igbo" },
  { code: "am", name: "አማርኛ", en: "Amharic" },
  { code: "zu", name: "isiZulu", en: "Zulu" },
  { code: "az", name: "Azərbaycan", en: "Azerbaijani" },
  { code: "kk", name: "Қазақ", en: "Kazakh" },
  { code: "uz", name: "Oʻzbek", en: "Uzbek" },
  { code: "hy", name: "Հայերեն", en: "Armenian" },
  { code: "ka", name: "ქართული", en: "Georgian" },
  { code: "mn", name: "Монгол", en: "Mongolian" },
];

export function langName(code) {
  const l = TRANSLATE_LANGS.find((x) => x.code === code);
  return l ? l.name : code;
}
